import React from 'react';

const ResumePDFReport = React.forwardRef(({ data }, ref) => {
  if (!data) return null;

  return (
    <div 
      className="fixed -left-[9999px]" // Keeps it reliably completely hidden from viewport layout
    >
      {/* 
        This is the inner container we target with html2canvas.
        We fix it to 794px which is optimal A4 portrait pixel width rendering at 96 DPI.
      */}
      <div 
        ref={ref} 
        style={{
          width: '794px',
          minHeight: '1123px',
          padding: '60px 40px',
          background: '#ffffff',
          color: '#000000',
          fontFamily: "Arial, sans-serif"
        }}
      >
        {/* Header */}
        <div style={{ borderBottom: '2px solid #0f172a', paddingBottom: '20px', marginBottom: '30px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 style={{ fontSize: '32px', fontWeight: 'bold', margin: '0 0 5px 0', letterSpacing: '-0.5px', color: '#0f172a' }}>Resume Analysis Report</h1>
            <p style={{ fontSize: '14px', color: '#64748b', margin: 0, textTransform: 'uppercase', letterSpacing: '1px' }}>Generated by Sentinel AI</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ background: data.atsScore >= 80 ? '#22c55e' : data.atsScore >= 50 ? '#f59e0b' : '#ef4444', color: '#fff', padding: '12px 24px', borderRadius: '8px', display: 'inline-block' }}>
              <span style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '1px', opacity: 0.9 }}>ATS Score</span>
              <div style={{ fontSize: '32px', fontWeight: 'bold', lineHeight: 1, marginTop: '2px' }}>{data.atsScore}/100</div>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        {data.executiveSummary && (
          <div style={{ marginBottom: '30px', background: '#f8fafc', padding: '24px', borderLeft: '4px solid #3b82f6', borderRadius: '0 8px 8px 0' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '10px', color: '#1e293b', textTransform: 'uppercase', letterSpacing: '1px' }}>Executive Summary</h3>
            <p style={{ fontSize: '15px', lineHeight: 1.7, color: '#334155', margin: 0 }}>{data.executiveSummary}</p>
          </div>
        )}

        {/* Role Profile */}
        {data.roleSpecificFeedback && data.roleSpecificFeedback.detectedRole && (
          <div style={{ marginBottom: '35px' }}>
            <h3 style={{ fontSize: '18px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '8px', marginBottom: '15px', color: '#1e293b' }}>
              Targeted Role Profile: <span style={{ color: '#d946ef' }}>{data.roleSpecificFeedback.detectedRole}</span>
            </h3>
            <ul style={{ margin: 0, paddingLeft: '20px', color: '#334155', fontSize: '15px', lineHeight: 1.7 }}>
              {data.roleSpecificFeedback.suggestions.map((s, i) => (
                <li key={i} style={{ marginBottom: '10px' }}>{s}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Section Scores */}
        {data.sectionScores && (
          <div style={{ marginBottom: '35px' }}>
            <h3 style={{ fontSize: '18px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '8px', marginBottom: '15px', color: '#1e293b' }}>Section Breakdown</h3>
            <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
              {Object.entries(data.sectionScores).map(([k, v]) => (
                <div key={k} style={{ flex: '1 1 calc(50% - 20px)', background: '#f8fafc', padding: '16px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ fontWeight: 'bold', color: '#334155', textTransform: 'uppercase', fontSize: '13px', letterSpacing: '0.5px' }}>{k}</span>
                    <span style={{ fontWeight: 'bold', color: v >= 8 ? '#16a34a' : v >= 5 ? '#d97706' : '#dc2626' }}>{v}/10</span>
                  </div>
                  <div style={{ height: '6px', background: '#e2e8f0', borderRadius: '3px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${v*10}%`, background: v >= 8 ? '#16a34a' : v >= 5 ? '#d97706' : '#dc2626' }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Missing Keywords */}
        {data.missingKeywords && data.missingKeywords.length > 0 && (
          <div style={{ marginBottom: '35px' }}>
            <h3 style={{ fontSize: '18px', fontWeight: 'bold', borderBottom: '1px solid #fee2e2', paddingBottom: '8px', marginBottom: '15px', color: '#ef4444' }}>Critical Keyword Gaps</h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {data.missingKeywords.map((kw, i) => (
                <span key={i} style={{ padding: '6px 12px', background: '#fef2f2', border: '1px solid #fca5a5', color: '#991b1b', borderRadius: '4px', fontSize: '13px', fontWeight: 'bold' }}>{kw}</span>
              ))}
            </div>
          </div>
        )}

        {/* Tone & Formatting */}
        <div style={{ display: 'flex', gap: '20px' }}>
          {data.toneCheck && (
            <div style={{ flex: 1, background: '#f8fafc', padding: '20px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '8px', marginBottom: '12px', color: '#4f46e5' }}>Tone Analysis</h3>
              <div style={{ fontSize: '14px', lineHeight: 1.6, color: '#334155' }}>
                <div style={{ marginBottom: '10px' }}><strong>Quantification:</strong> {data.toneCheck.quantification}</div>
              </div>
            </div>
          )}
          {data.formattingTips && (
            <div style={{ flex: 1, background: '#f8fafc', padding: '20px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '8px', marginBottom: '12px', color: '#0891b2' }}>Formatting</h3>
              <div style={{ fontSize: '14px', lineHeight: 1.6, color: '#334155' }}>
                <div style={{ marginBottom: '10px' }}><strong>Length:</strong> {data.formattingTips.length}</div>
                <div style={{ marginBottom: '10px' }}><strong>Dates:</strong> {data.formattingTips.datesFormat}</div>
              </div>
            </div>
          )}
        </div>

      </div>
    </div>
  );
});

export default ResumePDFReport;
