import React from 'react';

const ResumePDFReport = React.forwardRef(({ data }, ref) => {
  if (!data) return null;

  const scoreColor = data.atsScore >= 80 ? '#16a34a' : data.atsScore >= 50 ? '#d97706' : '#dc2626';

  return (
    <div
      className="absolute left-[-9999px] top-0"
    >
      <div
        ref={ref}
        style={{
          width: '794px',
          padding: '40px 40px 50px',
          background: '#ffffff',
          color: '#1e293b',
          fontFamily: "'Segoe UI', Arial, sans-serif",
          fontSize: '14px',
          lineHeight: 1.6,
        }}
      >
        {/* ── Header ── */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: '18px', borderBottom: '3px solid #0f172a', marginBottom: '24px' }}>
          <div>
            <h1 style={{ fontSize: '26px', fontWeight: 'bold', margin: '0 0 4px', color: '#0f172a' }}>Resume Analysis Report</h1>
            <p style={{ fontSize: '12px', color: '#94a3b8', margin: 0, textTransform: 'uppercase', letterSpacing: '1.5px' }}>Generated by Resume IQ</p>
          </div>
          <div style={{ background: scoreColor, color: '#ffffff', padding: '14px 28px', borderRadius: '10px', textAlign: 'center', minWidth: '110px' }}>
            <div style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '1.5px', marginBottom: '4px', fontWeight: 600 }}>ATS Score</div>
            <div style={{ fontSize: '36px', fontWeight: 'bold', lineHeight: 1 }}>{data.atsScore}<span style={{ fontSize: '16px', fontWeight: 400, opacity: 0.85 }}>/100</span></div>
          </div>
        </div>

        {/* ── Executive Summary ── */}
        {data.executiveSummary && (
          <div style={{ marginBottom: '22px', background: '#f1f5f9', padding: '18px 20px', borderLeft: '4px solid #3b82f6', borderRadius: '0 8px 8px 0' }}>
            <h3 style={{ fontSize: '13px', fontWeight: 'bold', marginBottom: '8px', color: '#475569', textTransform: 'uppercase', letterSpacing: '1px', margin: '0 0 8px' }}>Executive Summary</h3>
            <p style={{ fontSize: '14px', lineHeight: 1.7, color: '#334155', margin: 0 }}>{data.executiveSummary}</p>
          </div>
        )}

        {/* ── Role Profile ── */}
        {data.roleSpecificFeedback && data.roleSpecificFeedback.detectedRole && (
          <div style={{ marginBottom: '22px' }}>
            <h3 style={{ fontSize: '15px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '12px', color: '#1e293b' }}>
              Targeted Role: <span style={{ color: '#d946ef' }}>{data.roleSpecificFeedback.detectedRole}</span>
            </h3>
            <ul style={{ margin: 0, paddingLeft: '18px', color: '#334155', fontSize: '13px', lineHeight: 1.7 }}>
              {data.roleSpecificFeedback.suggestions.map((s, i) => (
                <li key={i} style={{ marginBottom: '6px' }}>{s}</li>
              ))}
            </ul>
          </div>
        )}

        {/* ── Section Scores ── */}
        {data.sectionScores && (
          <div style={{ marginBottom: '22px' }}>
            <h3 style={{ fontSize: '15px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '12px', color: '#1e293b' }}>Section Breakdown</h3>
            <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
              {Object.entries(data.sectionScores).map(([k, v]) => (
                <div key={k} style={{ flex: '1 1 calc(50% - 12px)', background: '#f8fafc', padding: '12px 14px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <span style={{ fontWeight: 'bold', color: '#334155', textTransform: 'uppercase', fontSize: '11px', letterSpacing: '0.5px' }}>{k}</span>
                    <span style={{ fontWeight: 'bold', fontSize: '13px', color: v >= 8 ? '#16a34a' : v >= 5 ? '#d97706' : '#dc2626' }}>{v}/10</span>
                  </div>
                  <div style={{ height: '5px', background: '#e2e8f0', borderRadius: '3px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${v * 10}%`, background: v >= 8 ? '#16a34a' : v >= 5 ? '#d97706' : '#dc2626', borderRadius: '3px' }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Missing Keywords ── */}
        {data.missingKeywords && data.missingKeywords.length > 0 && (
          <div style={{ marginBottom: '22px' }}>
            <h3 style={{ fontSize: '15px', fontWeight: 'bold', borderBottom: '1px solid #fee2e2', paddingBottom: '6px', marginBottom: '12px', color: '#ef4444' }}>Critical Keyword Gaps</h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
              {data.missingKeywords.map((kw, i) => (
                <span key={i} style={{ padding: '4px 10px', background: '#fef2f2', border: '1px solid #fca5a5', color: '#991b1b', borderRadius: '4px', fontSize: '12px', fontWeight: 600 }}>{kw}</span>
              ))}
            </div>
          </div>
        )}

        {/* ── Tone Analysis ── */}
        {data.toneCheck && (
          <div style={{ marginBottom: '14px', background: '#f8fafc', padding: '16px 18px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px', color: '#4f46e5', margin: '0 0 10px' }}>Tone Analysis</h3>
            <div style={{ fontSize: '13px', lineHeight: 1.6, color: '#334155' }}>
              {data.toneCheck.passiveVoice && data.toneCheck.passiveVoice.length > 0 && (
                <div style={{ marginBottom: '8px' }}><strong>Passive Voice:</strong> {data.toneCheck.passiveVoice.join('; ')}</div>
              )}
              {data.toneCheck.weakVerbs && data.toneCheck.weakVerbs.length > 0 && (
                <div style={{ marginBottom: '8px' }}><strong>Weak Verbs:</strong> {data.toneCheck.weakVerbs.join(', ')}</div>
              )}
              <div><strong>Quantification:</strong> {data.toneCheck.quantification}</div>
            </div>
          </div>
        )}

        {/* ── Formatting Tips ── */}
        {data.formattingTips && (
          <div style={{ marginBottom: '14px', background: '#f8fafc', padding: '16px 18px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
            <h3 style={{ fontSize: '14px', fontWeight: 'bold', borderBottom: '1px solid #e2e8f0', paddingBottom: '6px', marginBottom: '10px', color: '#0891b2', margin: '0 0 10px' }}>Formatting Review</h3>
            <div style={{ fontSize: '13px', lineHeight: 1.6, color: '#334155' }}>
              <div style={{ marginBottom: '8px' }}><strong>Length:</strong> {data.formattingTips.length}</div>
              {data.formattingTips.bulletStructure && (
                <div style={{ marginBottom: '8px' }}><strong>Bullets:</strong> {data.formattingTips.bulletStructure}</div>
              )}
              <div><strong>Dates:</strong> {data.formattingTips.datesFormat}</div>
            </div>
          </div>
        )}

        {/* ── Footer ── */}
        <div style={{ marginTop: '20px', paddingTop: '12px', borderTop: '1px solid #e2e8f0', textAlign: 'center', fontSize: '11px', color: '#94a3b8' }}>
          Generated on {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} • Resume IQ — AI-Powered Resume Analysis
        </div>
      </div>
    </div>
  );
});

export default ResumePDFReport;
